@baseUrl = http://localhost:5000/api
#Categories

# @name getAllCategories
GET {{baseUrl}}/categories

###
# @name addNewCategory
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "name":"Test thu"
}
###

###
# @name editCategory
PATCH {{baseUrl}}/categories/HycS1IV
Content-Type: application/json

{
    "name":"New laptop",
    "searchTerm": "new laptop"
}
###

###
# @name remveCategory
DELETE {{baseUrl}}/categories/HycS1IV
###